services:
  database:
    image: mongo:5
    container_name: mongodb
    restart: always
    environment:
      MONGODB_DATABASE: widgets
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
